"""Add password_hash to User

Revision ID: 95633065dca0
Revises: e204bbe74c9e
Create Date: 2025-03-21 07:03:44.256434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95633065dca0'
down_revision = 'e204bbe74c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
       batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))

    # Step 2: Set a default value for existing rows
    op.execute("UPDATE users SET password_hash = 'default_password' WHERE password_hash IS NULL")

    # Step 3: Alter the column to be NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
